### ISSUE TITLE
don't write in first person

### ISSUE THREAD

**Issue by jlcohoon** [csoderberg/OSF-Curriculum#23]
I might be outnumbered in this, but I think it makes more sense to not write this in first person. Not doing so means that the materials can more easily be shared as a print out or other document. It is also unlikely that the presenter will literally be reading from this as a script.

**Comment by csoderberg** [comment]
I went back and forth on this. While it's hopefully unlikely that someone will be reading verbatim, putting it in third person gave it this very formal, odd tone, whereas first person made it sound more like the reader and the 'speaker/writer' were in this together. So it sounded more constructive than lecturey. The SWC lessons that I was using as a general structure guide are also written in 1st person. 

Was it the general first person (so we's and Is), or specifically the 'I's'?

**Comment by evomellor** [comment]
I think that a mix of first and second person is appropriate given the desire for approachable, informal tones. First person suggests that the author is with you (either physically in the room, or physically removed from you, but "on your side" as you begin to use the OSF). 

Second person comes in more of the instructional aspects of these workshops: "Now you are going to set up an OSF account..." which works well for both handouts and written presentations.
