### ISSUE TITLE
Documenting: order of version control and registration

### ISSUE THREAD

**Issue by evomellor** [csoderberg/OSF-Curriculum#39]
The order of the two major parts of the "documenting" page do not match the order they are listed in the learning goals of that page. I was about to simply edit and submit a PR, but I'm not quite sure which is the better order: version control followed by registrations, or vice versa. I think version control should probably go first because it is a more widely used feature.

**Comment by csoderberg** [comment]
Registrations should come first, since it's a sort of...'pre-registration' in this example (not actually, but it coming first will make that module easier to fit in once it exists)
